<a href="https://colab.research.google.com/github/Sinrez/pyCoursera/blob/master/lab_1_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №2
**Ответом на задание будет *.ipynb файл.**

Требования:
1. Лабораторная работа выполняется в данном шаблоне.
2. Удаление и добавление ячеек **не допускается**.
3. Код необходимо вводить только там, где присутствует комментарий `# вставить код сюда`.
4. Перед тем, как выложить работу в moodle, переименуйте файл по следующему шаблону **ФамилияИО.ipynb**. Например: если Вас зовут Иванов Иван Иванович, то имя файла будет выглядеть так **ИвановИИ.ipynb**.

Требования обусловлены автоматической проверкой кода в качестве входного контроля.

**`num_list`, `str_list`, `result_list`, `even_list`, `odd_list` уже объявлены в коде, повторно объявлять их не надо. Выполните следующую ячейку, и все списки будут доступны в остальных ячейках.**

In [ ]:
num_list = []
str_list = []
result_list = []
even_list = []
odd_list = []

#### Пример ввода чисел
Здесь приведен пример организации ввода. Дополнительный контроль ввода организовывать не надо. По умолчанию считаем, что пользователи вводят корректные данные.

In [ ]:
while input('Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)? ') != 'н':
    val = int(input("Введите значение "))
    print(val, type(val))

### Задача № 1

Реализуйте алгоритм ввода списка `num_list`, который должен хранить целые числа. Используйте функцию `input()` для организации ввода. Перед добавлением нового элемента необходимо уточнять у пользователя надо ли продолжить/прекратить ввод. При этом положительные элементы необходимо добавлять непосредственно в начало списка, а отрицательные элементы - в хвост списка.

#### Решение

In [ ]:
# вставить код сюда
def make_list() -> None:
  lst_neg = []
  while input('Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)? ').lower().replace("n","н") != 'н':
    val = int(input("Введите значение "))
    if val >=0:
      num_list.append(val)
    else:
      lst_neg.append(val)
  num_list.extend(lst_neg)

if __name__ == '__main__':
  make_list()
  print(num_list)




Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)?  
Введите значение 1
Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)?  
Введите значение 4
Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)?  
Введите значение -1
Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)?  
Введите значение -5
Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)?  
Введите значение 0
Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)? n
[1, 2, 1, 2, 1, 4, 0, -1, -5]


### Задача № 2

Произведите ввод двух целых чисел, разработайте алгоритм удаления из списка `num_list` всех элементов между двумя с заданными значениями. Поиск первого необходимо осуществлять с начала списка, поиск второго - с конца, ищем до первого найденного. После модификации списка выведите его.

**Пример**:

Имеем `num_list = [2, 8, 5, 8, -14, -10, -3, -7]`.

Если введены числа `8` и `-10`, то должны вывести `num_list = [2, 8, -10, -3, -7]`.

#### Решение

In [ ]:
# вставить код сюда
# num_list = [2, 8, 5, 8, -14, -10, -3, -7]

def del_val_lst(lst) -> None:
     val1 = int(input("Введите первое значение: "))
     val2 = int(input("Введите второе значение: "))
     i1 = lst.index(val1)
     i2 = 0
     for i in range(len(lst)-1,-1,-1):
       if lst[i] == val2:
         i2 = i
     del lst[i1+1:i2]

if __name__ == '__main__':
  del_val_lst(num_list)
  print(num_list)

Введите первое значение: 8
Введите второе значение: -10
[2, 8, -10, -3, -7]


### Задача № 3

Реализуйте алгоритм ввода списка `str_list`, который должен хранить строки (используйте `input()`). Длина `str_list` заранее не известна, поэтому ввод организуйте по аналогии с задачей №1.

#### Решение

In [ ]:
# вставить код сюда
def in_str_list(lst) -> None:
  while input('Хотите ввести строку? (любой символ, кроме "н", для продолжения)? ').lower().replace("n","н") != 'н':
    lst.append(input('Введите строку, для сохранения нажмите Enter: ').strip())

if __name__ == '__main__':
  in_str_list(str_list)
  print(str_list)


Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)?  
Введите строку, для сохранения нажмите Enter: sdfsfssds
Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)?  
Введите строку, для сохранения нажмите Enter: sdfsfsd
Хотите добавить еще одно значение (любой символ, кроме "н", для продолжения)? n
['sdfsfssds', 'sdfsfsd']


### Задача № 4

Напишите алгоритм подсчета количества слов палиндромов (одинаково читаются слева направо и справа налево) в списке `str_list`. Выведите полученное значение.

**Пример**:

Имеем `str_list = ["мою", "маму", "зовут", "анна", "она", "сломала", "шалаш"]`.

Палиндромами являются слова `"анна"` и `"шалаш"`, а их количество равно 2.

#### Решение

In [ ]:
# вставить код сюда
#str_list = ["мою", "маму", "зовут", "анна", "она", "сломала", "шалаш"]

def count_poly(lst) ->int:
  cnt = 0
  for l in lst:
    if l == l[::-1]:
      cnt += 1
  return cnt 

if __name__ == '__main__':
  print(count_poly(str_list))



2


### Задача № 5

Создайте (посредством генератора списков) список с именем `result_list`. Элементы нового списка должны быть равны <br> $x^3-4, где x\in$`num_list` из задачи №2. Выведите полученный список.

**Пример**:

Имеем `num_list = [2, 8, -10, -3, -7]`.

Должны получить `result_list = [4, 508, -1004, -31, -347]`.

#### Решение

In [ ]:
# вставить код сюда
#num_list = [2, 8, -10, -3, -7]

result_list = [n**3-4 for n in num_list]
result_list

[4, 508, -1004, -31, -347]

### Задача № 6

С помощью срезов создайте из списка `result_list` два новых: `even_list` и `odd_list`. Первый должен содержать четные по индексу элементы, второй - нечетные по индексу. Выведите полученные списки.

**Пример**:

Имеем `result_list = [4, 508, -1004, -31, -347]`.

Должны получить `even_list = [4, -1004, -347]` `odd_list = [508, -31]`.

#### Решение

In [ ]:
# вставить код сюда
# result_list = [4, 508, -1004, -31, -347]

even_list = result_list[::2]
odd_list = result_list[1::2]

# print(even_list)
# print()
# print(odd_list)


[4, -1004, -347]

[508, -31]


### Задача № 7

Сгенерировать множества (тип `set`) всех возможных сочетаний ($k\in [0; N]$) из `N` элементов (символы латинского алфавита). `N` – задается пользователем ($N\in [1; 26]$). Полученные множества сохранить в словаре, где ключом будет являться кортеж, состоящий из порядкового номера сгенерированного множества  $[1; 2^{n}]$ и строки, которая содержит все элементы текущего множества, отсортированные в лексикографическом порядке.

**Пример**:

Имеем `N = 3`.

Должны получить 

`{(1, ''): set(),
(2, 'a'): {‘a’},
(3, 'b'): {‘b’},
(4, 'c'): {‘c’},
(5, 'ab'): {‘b’, ‘a’},
(6, 'ac'): {‘a’, ‘c’},
(7, 'bc'): {‘c’, ‘b’},
(8, 'abc'): {‘b’, ‘a’,‘c’}}`

#### Решение

In [ ]:
# вставить код сюда
from string import ascii_lowercase
from itertools import chain, combinations, permutations

def powerset(list_name) -> tuple:
    s = list(list_name)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

def set_gen() -> set:
  try:
    n = int(input('Введите n от 1 до 26: '))
  except Exception as e:
    print(f"Ошибка ввода: {e}")

  lst_dgt = [l for l in range(n+1)] #список чисел до n
  alph = list(ascii_lowercase)[:n] #срез списка-алфавита до n
  cache = [list(p) for p in powerset(alph)]  #промежуточный список для обработки сочетаний букв
  # print(cache)
  cache_shuflle = [] #для перемешивания комбинаций
  for ch in cache:
    if len(ch) >= 2:
      seq = permutations(ch)
      for p in list(seq):
        cache_shuflle.append(tuple(p))
    else:
      cache_shuflle.append(tuple(ch))

  set_shuflle = list(set(cache_shuflle))
  # print(cache_shuflle)
  set_shuflle2 = sorted(set_shuflle, key=lambda x: x)
  # set_shuflle2 = sorted(set_shuflle, key=lambda x: x[::-1])
  # print(set_shuflle2)

  dict_cache = {}
  for i in range(2**n):
    dict_cache[(i+1,''.join(set_shuflle2[i]))] = set(set_shuflle2[i])
  print(dict_cache)

if __name__ == '__main__':
  set_gen()

Введите n от 1 до 26: 5
{(1, ''): set(), (2, 'a'): {'a'}, (3, 'ab'): {'a', 'b'}, (4, 'abc'): {'a', 'c', 'b'}, (5, 'abcd'): {'d', 'a', 'c', 'b'}, (6, 'abcde'): {'a', 'c', 'd', 'b', 'e'}, (7, 'abce'): {'a', 'c', 'b', 'e'}, (8, 'abced'): {'a', 'c', 'd', 'b', 'e'}, (9, 'abd'): {'d', 'a', 'b'}, (10, 'abdc'): {'d', 'a', 'c', 'b'}, (11, 'abdce'): {'a', 'c', 'd', 'b', 'e'}, (12, 'abde'): {'d', 'a', 'b', 'e'}, (13, 'abdec'): {'a', 'c', 'd', 'b', 'e'}, (14, 'abe'): {'a', 'b', 'e'}, (15, 'abec'): {'a', 'c', 'b', 'e'}, (16, 'abecd'): {'a', 'c', 'd', 'b', 'e'}, (17, 'abed'): {'d', 'a', 'b', 'e'}, (18, 'abedc'): {'a', 'c', 'd', 'b', 'e'}, (19, 'ac'): {'a', 'c'}, (20, 'acb'): {'a', 'c', 'b'}, (21, 'acbd'): {'d', 'a', 'c', 'b'}, (22, 'acbde'): {'a', 'c', 'd', 'b', 'e'}, (23, 'acbe'): {'a', 'c', 'b', 'e'}, (24, 'acbed'): {'a', 'c', 'd', 'b', 'e'}, (25, 'acd'): {'d', 'a', 'c'}, (26, 'acdb'): {'d', 'a', 'c', 'b'}, (27, 'acdbe'): {'a', 'c', 'd', 'b', 'e'}, (28, 'acde'): {'d', 'a', 'c', 'e'}, (29, 'acdeb')