f1 = open("shopping_list_1.txt", encoding="utf8")
f1.seek(0)
f2 = open("shopping_list_2.txt", encoding="utf8")
f2.seek(0)
f3 = open("shopping_list_3.txt", encoding="utf8")
f3.seek(0)

f1 = f1.read().split('\n')
f2 = f2.read().split('\n')
f3 = f3.read().split('\n')
f = set(f1+f2+f3)
f = sorted(f)
f = '\n'.join(f)
f4 = open("shopping_list.txt", "w+")
f4.write(f)